version: '2'

networks:
  exposed_services:
    external:
      name: exposed_services

services:
  minimal-docker:
    image: local/example-api
    expose:
      - "8080"
    env_file:
      - .env
    networks:
      - exposed_services